################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@host = http://localhost:{{$dotenv PORT}}

### GET /v1/posts
GET {{host}}/v1/posts

### GET /v1/posts/:id
GET {{host}}/v1/posts/2

### GET /v1/posts/category/:id
GET {{host}}/v1/posts/category/3

### POST /v1/cadex
POST {{host}}/v1/posts
Content-Type: application/json

{
    "title": "Hey, it's me again",
    "slug": "hey-it-s-me-again",
    "excerpt": "I have something new to say...",
    "content": "Meh.Ut enimblabla ad <em>minim veniam</em>, <strong>laboris nisi</strong>.",
    "category_id": 4
}

### GET /v1/categories
GET {{host}}/v1/categories
